<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MultiWishlist
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

?>
<?php
/* @var $this Bss\MultiWishlist\Block\MultiWishlist */
?>
<span class="mess">
	<span class="not-empty-name"><?php echo __('The wishlist name can\'t be left blank') ?></span>
</span>
<script type="text/x-magento-init">
     {
        "*": {
            "Bss_MultiWishlist/js/bss_wishlist": {
                "is_redirect": <?php /* @escapeNotVerified */ echo $block->isRedirect() ?>,
                "url_redirect": "<?php /* @escapeNotVerified */ echo $block->getUrlWishlist() ?>",
                "url_popup":"<?php /* @escapeNotVerified */ echo $block->getUrlPopup() ?>",
                "isLoggedIn": "<?php echo $block->isCustomerLoggedIn() ?>"
            }
        }
    }
</script>