<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MultiWishlist
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

?>
<?php
/* @var $this Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart */
?>
<?php $childs = $block->getChildNames(); ?>
<?php foreach ($childs as $childName): ?>
	<?php
	
	if ( $childName == 'product.price.render.wishlist' && in_array('customer.wishlist.item.options', $childs) && trim($block->getLayout()->renderElement('customer.wishlist.item.options', false)) != '') {
		echo /* @noEscape */ $block->getItemPriceHtml($block->getItem(),'wishlist_configured_price',
                                    \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                                    ['item' => $block->getItem()]);
	} else {
		echo /* @noEscape */  $block->getLayout()->renderElement($childName, false);
	}
	?>
<?php endforeach;?>
