<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MultiWishlist
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

?>
<?php
/* @var $this Magento\Wishlist\Block\Customer\Wishlist */
?>
<!--<h1 class="page-title">-->
<!--    <span class="base" data-ui-id="page-title-wrapper">My Data Feed List</span>-->
<!--</h1>-->

<form action="<?php echo $block->getUrl('multiwishlist/index/create') ?>" method="post" id="wishlist-form-validation">
    <?php echo $block->getBlockHtml('formkey')?>
    <table class="clean-table linearize-table">
        <tr>
            <td>
                <div class="content-create-wl">
                    <input required id="new_wlname" class="input-text required-entry" type="text"  placeholder="<?php echo __('Enter Feed List Name') ?>"  name="new_wlname"/>
                </div>
                <button class="action primary create-wl" title="<?php echo __('Create Data Feed List') ?>"  type="submit" ><span><span><?php echo __('Create Data Feed List') ?></span></span></button>
                <span class="clearfix"></span>
            </td>
        </tr>
    </table>
</form>

<form action="<?php echo $block->getUrl('multiwishlist/index/add') ?>" method="post">
    <?php echo $block->getBlockHtml('formkey')?>
    <label>Product ID</label>
    <input required id="new_product" name="new_product" type="text"
           class="input-text mwishlist_name"/>
    <!--                id="product_--><?php //echo $id ?><!--"-->
    <button class="button deletewl" title="<?php echo __('ADD') ?>" type="submit"
    <span><span><?php echo __('ADD') ?></span></span>
    </button>
<!--               <button class="button deletewl" title="--><?php //echo __('ADD') ?><!--" type="submit"-->
<!--                       onClick="window.location = '--><?php //echo $block->getUrl('multiwishlist/index/add'); ?><!--';">-->
                 <span><span><?php //echo __('ADD') ?><!--</span></span>-->
<!--              </button>-->
</form>

<script type="text/x-magento-init">
     {
        "*": {
            "validation": {
            }
        }
    }
</script>
