<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MultiWishlist
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .btn {
        border: none;
        color: white;
        padding: 12px 16px;
        font-size: 16px;
        cursor: pointer;
    }

    /* Darker background on mouse-over */
    .btn:hover {
        background-color: RoyalBlue;
    }

    #customers {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #customers td, #customers th {
        border: 1px solid #d1d1d1;
        padding: 8px;
    }

    #customers tr:nth-child(even){background-color: #f2f2f2;}

    #customers tr:hover {background-color: #ddd;}

    #customers th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: center;
        background-color: #408dc3;
        color: white;
    }
</style>


<?php
/* @var $this Magento\Wishlist\Block\Customer\Wishlist\Items */
?>
<?php
$columns = $block->getColumns();
$countColumns = count($columns);
$countItem = count($block->getItems());
$helper = $this->helper('Bss\MultiWishlist\Helper\Data');
$multiWishlist = $helper->getLabelIds();
$i = 0;
foreach ($multiWishlist as $id):
    $i++;
    $array = [];
    $array = $helper->getWishlistItemsCollection($id);
    ?>
    <div id="view<?php echo $i; ?>" class="tabs-wishlist">
        <input type="hidden" name="wishlist-id" class="wishlist-id" value="<?php echo $id ?>">
        <?php if ($i > 1): ?>
            <div class="editwl_link">
                <input name="mwishlist_name_<?php echo $id ?>" id="mwishlist_name_<?php echo $id ?>"
                       value="<?php echo $helper->getWishlistName($id) ?>" type="text"
                       class="input-text mwishlist_name"/>
                <button data-form="<?php echo $block->getUrl('multiwishlist/index/edit') ?>"
                        class="action primary edit_wishlist_button" id="editwl_<?php echo $id ?>" title="<?php echo __('Edit') ?>"
                        type="button"><span><span><?php echo __('Edit') ?></span></span>
                </button>
                <button class="button deletewl" title="<?php echo __('Delete') ?>" type="button"
                        onClick="if(confirm('Do you really want to delete this Wishlist along with all products in it?'))window.location = '<?php echo $block->getUrl('multiwishlist/index/delete',
                            ['mWishlistId' => $id, 'form_key' => $block->getFormKey()]); ?>';">
                    <span><span><?php echo __('Delete') ?></span></span>
                </button>

                <button class="button deletewl" title="<?php echo __('Add Product') ?>" type="button"
                        onClick="" style="margin-left: 400px;"><i class="fa fa-plus"></i>
                    <span><span><?php echo __('Add Products') ?></span></span>
                </button>
                <br>
<!--       sample add product function-->
<!--                <form action="--><?php //echo $block->getUrl('multiwishlist/index/add') ?><!--" method="post" >-->
                <label>Product ID</label>
                <input required id="new_product" name="new_product" type="text"
                       class="input-text mwishlist_name"/>
<!--                id="product_--><?php //echo $id ?><!--"-->
<!--                    <button class="button deletewl" title="--><?php //echo __('ADD') ?><!--" type="submit"-->
<!--                    <span><span>--><?php //echo __('ADD') ?><!--</span></span>-->
<!--                    </button>-->
              <button class="button deletewl" title="<?php echo __('ADD') ?> " type="submit"
                        onClick="window.location = '<?php echo $block->getUrl('multiwishlist/index/add'); ?>';">
                  <span><span><?php echo __('ADD') ?></span></span>
              </button>
<!--</form>-->
<!--                <button data-form="--><?php //echo $block->getUrl('multiwishlist/index/add') ?><!--"-->
<!--                        class="action primary edit_wishlist_button" id="addproduct_--><?php //echo $id ?><!--" title="--><?php //echo __('ADD') ?><!--"-->
<!--                        type="button"><span><span>--><?php //echo __('ADD') ?><!--</span></span>-->
<!--                </button>-->

            </div>
        <br>
<!--            <br>-->
<!---->
<!--        <form action="test.phtml" method="get">-->
<!--            <label><b>Product ID<b/></label>-->
<!--            <input type="search" name="" class="" value="" style="width: 150px;"  placeholder="--><?//=__('Search Product ID...') ?><!--">-->
<!--            <button title="--><?php //echo __('Add Product') ?><!--" type="submit" class="action search">-->
<!--                <span><span>--><?php //echo __('Add') ?><!--</span></span>-->
<!--            </button>-->
<!--        </form>-->

            <br><br>
        <?php if (!empty($array->getData())): ?>
            <div class="products-grid wishlist">
                <?php $iterator = 1; ?>
            <table id="customers">
                <tr>
                    <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Category</th>
                </tr>
             <ol class="product-items">
                    <?php foreach ($array as $item): ?>
                 <tr>
                     <td><?php echo $item->getProductId();?></td>
<!--                 <td>-->
<!--                 --><?php ///* @escapeNotVerified */
//                        echo ($iterator++ == 1) ? '<li data-row="product-item" class="product-item" id="item_' . $item->getId() . '">' : '</li><li class="product-item" id="item_' . $item->getId() . '">' ?>
<!--                        <div class="product-item-info">-->
<!--                            --><?php //foreach ($columns as $column): ?>
<!--                                --><?php //$column->setItem($item);
//                                echo $column->toHtml($item); ?>
<!--                            <br>-->
<!--                            --><?php //endforeach; ?>
<!---->
<!--                        </div>-->
<!--                        --><?php //echo ($iterator == $countItem + 1) ? '</li>' : '' ?>
<!--                 </td>-->
                        <td><?php echo $item->getName();?></td>
                        <td>
                            <?php
                            $categories = $item->getProduct()->getCategoryCollection()
                                ->addAttributeToFilter('entity_id', $item->getProduct()->getCategoryIds());

                            foreach ($categories as $category): ?>
                            <?php echo $category->getId(); ?>,
                            <?php endforeach; ?>
                        </td>
                        </tr>
                    <?php endforeach; ?>
                </ol>
            </table>
        </div>
            <?php endif; ?>


            <div class="clearfix"></div>
        <?php endif; ?>
        <div class="wltable">
            <table class="clean-table linearize-table" id="wishlist-table">
                <thead>
                <?php if (!empty($array->getData())): ?>
                    <tr>
                        <?php
                        /* @var $column Magento\Wishlist\Block\Customer\Wishlist\Item\Column */
                        foreach ($columns as $column):
                            $_blockName = str_replace('.', '-', strtolower($column->getNameInLayout()));
                            ?>
                            <th class="<?php echo $_blockName; ?>"><?php echo $column->getTitle(); ?></th>
                        <?php endforeach; ?>
                    </tr>
                <?php endif; ?>
                </thead>
                <tbody>

                <?php if (!empty($array->getData())): ?>
                    <div class="products-grid wishlist">

                        <?php $iterator = 1; ?>
            <?php if ($i > 1): ?>
<!--                <p>--><?php //echo $i?><!--</p>-->

            <?php elseif ($i = 1): ?>
               <ol class="product-items">
                    <?php foreach ($array as $item): ?>
                        <?php /* @escapeNotVerified */
                        echo ($iterator++ == 1) ? '<li data-row="product-item" class="product-item" id="item_' . $item->getId() . '">' : '</li><li class="product-item" id="item_' . $item->getId() . '">' ?>
                        <div class="product-item-info">
                            <?php foreach ($columns as $column): ?>
                                <?php $column->setItem($item);
                                echo $column->toHtml($item); ?>
                            <?php endforeach; ?>
                        </div>
                        <?php echo ($iterator == $countItem + 1) ? '</li>' : '' ?>
                    <?php endforeach; ?>

                </ol>
            <?php endif; ?>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" name="do" title="<?php echo __('Update Wish List') ?>" class="action update">
                                    <span><?php echo __('Update Wish List') ?></span>
                                </button>
                                <button data-url="<?php echo $block->getUrl('multiwishlist/index/share') ?>"
                                        data-value="<?php echo $id ?>"
                                        class="action share_wishlist_button"
                                        id="share_wishlist_<?php echo $id ?>" title="<?php echo __('Share Wish List') ?>" type="button">
                                    <span><span><?php echo __('Share Wish List') ?></span></span>
                                </button>
                                <button type="button" id="add_all_cart_<?php echo $id ?>" data-value="<?php echo $id ?>"
                                        data-role="all-tocart" title="<?php /* @escapeNotVerified */
                                echo __('Add All to Cart') ?>" class="action tocart">
                                    <span><?php /* @escapeNotVerified */
                                        echo __('Add All to Cart') ?></span>
                                </button>
<?php if ($i > 1): ?>
                                <button type="button" id="magento_<?php echo $id ?>" data-value="<?php echo $id ?>"
                                        data-role="" title="<?php /* @escapeNotVerified */
                                echo __('Download for Magento') ?>" class="btn" style="background-color: #FF7034;"><i class="fa fa-download"></i>
                                    <span><?php /* @escapeNotVerified */
                                        echo __('Magento') ?></span>
                                </button>
                                <button type="button" id="woo_<?php echo $id ?>" data-value="<?php echo $id ?>"
                                        data-role="" title="<?php /* @escapeNotVerified */
                                echo __('Download for WooCommerce') ?>" class="btn" style="background-color: #96588a;"><i class="fa fa-download"></i>
                                    <span><?php /* @escapeNotVerified */
                                        echo __('WOO') ?></span>
                                </button>
<?php endif; ?>

                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <tr>
                       <td colspan="<?php echo $countColumns; ?>"
                            class="wishlist-empty"><?php echo __('This Wish List has no Items'); ?></td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
        <?php foreach ($columns as $column): ?>
            <?php echo $column->getAdditionalHtml(); ?>
        <?php endforeach; ?>

        <script type="text/x-magento-init">
             {
                "*": {
                    "wishlisttable": {
                    }
                }
            }
        </script>
    </div>
<?php endforeach; ?>
